auth:
  type: DISABLED

spring:
  codec:
    max-in-memory-size: -1
  webflux:
    multipart:
      max-in-memory-size: -1

management:
  endpoint:
    info:
      enabled: true
    health:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "info,health,prometheus"

springdoc:
  path: /swagger
  api-docs:
    enabled: ${SWAGGER_UI_ENABLED:false}
  swagger-ui:
    enabled: ${SWAGGER_UI_ENABLED:false}
    url: /openapi/mykafka-ui-api.yaml
    urls:
      - name: mykafka-ui
        url: /openapi/mykafka-ui-api.yaml
    config-url: null
  override-with-generic-response: true

logging:
  level:
    root: INFO
    io.kafbat.ui: DEBUG
    reactor.netty.http.server.AccessLog: INFO
    org.hibernate.validator: WARN

