auth:
  type: DISABLED

cooperative-offset-reset:
  enabled: ${KAFBAT_UI_COOPERATIVE_OFFSET_RESET_ENABLED:false}
  command-topic: ${KAFBAT_UI_COOPERATIVE_OFFSET_RESET_COMMAND_TOPIC:__kui-cooperative-reset-commands}
  acknowledgement-topic: ${KAFBAT_UI_COOPERATIVE_OFFSET_RESET_ACK_TOPIC:__kui-cooperative-reset-acks}
  timeout: ${KAFBAT_UI_COOPERATIVE_OFFSET_RESET_TIMEOUT:30s}
  auto-create-topics: ${KAFBAT_UI_COOPERATIVE_OFFSET_RESET_AUTO_CREATE_TOPICS:false}

spring:
  codec:
    max-in-memory-size: ${KAFBAT_UI_CODEC_MAX_IN_MEMORY_SIZE:16MB}
  webflux:
    multipart:
      max-in-memory-size: ${KAFBAT_UI_MULTIPART_MAX_IN_MEMORY_SIZE:10MB}

management:
  endpoint:
    info:
      enabled: true
    health:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "info,health,prometheus"

springdoc:
  path: /swagger
  api-docs:
    enabled: ${SWAGGER_UI_ENABLED:false}
  swagger-ui:
    enabled: ${SWAGGER_UI_ENABLED:false}
    url: /openapi/mykafka-ui-api.yaml
    urls:
      - name: mykafka-ui
        url: /openapi/mykafka-ui-api.yaml
    config-url: null
  override-with-generic-response: true

logging:
  level:
    root: INFO
    io.kafbat.ui: ${KAFBAT_UI_LOG_LEVEL:INFO}
    reactor.netty.http.server.AccessLog: INFO
    org.hibernate.validator: WARN

